#!/usr/bin/env python3
"""Copy the seat count (and price) out of Dodo's record into a fact file the
site and its gates read, so no page ever carries a hand-typed number.

WHY THIS EXISTS. Every Dodo product's customer-facing activation message said
"up to 5 machines" while the product field and the governing entitlement both
said 3 — a promise of two machines nobody had bought. The message was corrected
in Dodo; this file is how the SITE stops drifting from it. A number typed into
HTML is a copy that cannot be re-read, and the 5 got there the same way.

The source is a fact file written straight from Dodo's product records by the
release toolchain (SOURCE, below). That writer exits 1 on any product /
entitlement mismatch, so a disagreement never reaches this file silently.

    python3 scripts/sync_product_facts.py            # write data/product-facts.json
    python3 scripts/sync_product_facts.py --check    # fail if it would change

⚠️ THE FACT FILE IS GENERATED. Do not edit data/product-facts.json by hand; the
next sync overwrites it and the gate will disagree with the page in between.
"""
from __future__ import annotations

import json
import pathlib
import sys

#: Outlier — Founders Lifetime. Named, because "whichever product happens to be
#: first" is how a page ends up quoting another product's seat count.
PRODUCT_ID = "pdt_0Nlgdu1f0s30YekSmpGwA"
SOURCE = pathlib.Path.home() / "ops" / "launch" / "dodo-facts.json"
OUT = pathlib.Path(__file__).resolve().parent.parent / "data" / "product-facts.json"


def build() -> dict:
    if not SOURCE.is_file():
        sys.exit(f"sync_product_facts: no source at {SOURCE} — run the Dodo fact writer first")
    src = json.loads(SOURCE.read_text(encoding="utf-8"))
    prod = (src.get("products") or {}).get(PRODUCT_ID)
    if not prod:
        sys.exit(f"sync_product_facts: {PRODUCT_ID} not in {SOURCE}")

    limit_p = prod.get("activations_limit_product")
    limit_e = prod.get("activations_limit_entitlement")
    seats = prod.get("seats")
    # The entitlement is the one that actually gates activation. If the three
    # disagree the site must not publish ANY of them — a number that is wrong
    # in a customer's favour is a promise, and wrong the other way is a
    # complaint. Refuse rather than pick.
    if not (limit_p == limit_e == seats) or not isinstance(seats, int) or seats < 1:
        sys.exit(f"sync_product_facts: seat fields disagree "
                 f"(product={limit_p} entitlement={limit_e} seats={seats}) — "
                 f"fix Dodo, do not publish a number")
    return {
        "_note": "GENERATED by scripts/sync_product_facts.py — do not edit by hand.",
        "product_id": PRODUCT_ID,
        "product_name": prod.get("name"),
        "seats": seats,
        "price_cents": prod.get("price_cents"),
        "activation_message": prod.get("activation_message_entitlement"),
        "source": str(src.get("source") or "dodo"),
        "read_at": src.get("read_at"),
    }


#: Fields that change on every read without changing what the file CLAIMS.
_VOLATILE = frozenset({"read_at"})


def main(argv: list[str]) -> int:
    facts = build()
    text = json.dumps(facts, indent=2, sort_keys=True) + "\n"
    if "--check" in argv:
        # ⚠️ COMPARE WHAT THE FILE CLAIMS, NOT WHEN IT WAS WRITTEN. A whole-text
        # comparison includes read_at, so every re-read of the vendor made the
        # published file "STALE" even when seats and price were identical. The
        # question --check exists to answer is "does the published file disagree
        # with the vendor?", and a timestamp cannot disagree with anything.
        # Wired into CI as it was, this would have been a red on every run that
        # happened to re-read — a gate that fails for a reason nobody can fix.
        cur_raw = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        try:
            cur_facts = json.loads(cur_raw) if cur_raw else {}
        except Exception:
            cur_facts = {}
        material = lambda d: {k: v for k, v in d.items() if k not in _VOLATILE}
        if material(cur_facts) != material(facts):
            print("sync_product_facts: data/product-facts.json is STALE — re-run without --check")
            for k in sorted(set(material(cur_facts)) | set(material(facts))):
                if cur_facts.get(k) != facts.get(k):
                    print(f"  {k}: published {cur_facts.get(k)!r} vs vendor {facts.get(k)!r}")
            return 1
        print(f"sync_product_facts: up to date (seats={facts['seats']}, read_at={facts['read_at']})")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"sync_product_facts: wrote {OUT.name} — seats={facts['seats']}, "
          f"price_cents={facts['price_cents']}, read_at={facts['read_at']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
